// <auto-generated />
namespace API_Angular_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class aya123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aya123));
        
        string IMigrationMetadata.Id
        {
            get { return "202006211603478_aya123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
